In [194]:
import numpy as np
import pandas as pd

In [195]:
data =pd.read_csv("data/household_power_consumption.txt",
 sep=";"
 ,low_memory=False)
data

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0
...,...,...,...,...,...,...,...,...,...
2075254,26/11/2010,20:58:00,0.946,0.000,240.430,4.000,0.000,0.000,0.0
2075255,26/11/2010,20:59:00,0.944,0.000,240.000,4.000,0.000,0.000,0.0
2075256,26/11/2010,21:00:00,0.938,0.000,239.820,3.800,0.000,0.000,0.0
2075257,26/11/2010,21:01:00,0.934,0.000,239.700,3.800,0.000,0.000,0.0
2075258,26/11/2010,21:02:00,0.932,0.000,239.550,3.800,0.000,0.000,0.0

In [196]:
data.drop(["Time", "Sub_metering_2", "Sub_metering_3"], axis=1, inplace=True)
data.head()

,Date,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1
0,16/12/2006,4.216,0.418,234.840,18.400,0.000
1,16/12/2006,5.360,0.436,233.630,23.000,0.000
2,16/12/2006,5.374,0.498,233.290,23.000,0.000
3,16/12/2006,5.388,0.502,233.740,23.000,0.000
4,16/12/2006,3.666,0.528,235.680,15.800,0.000

In [197]:
data.set_index("Date",inplace=True)
data.index = pd.to_datetime(data.index, dayfirst=True)
print(data.index.dtype)
data.head()

datetime64[ns]

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1
Date,,,,,
2006-12-16,4.216,0.418,234.840,18.400,0.000
2006-12-16,5.360,0.436,233.630,23.000,0.000
2006-12-16,5.374,0.498,233.290,23.000,0.000
2006-12-16,5.388,0.502,233.740,23.000,0.000
2006-12-16,3.666,0.528,235.680,15.800,0.000

In [198]:
def update_types(df):
        for col in df.columns :
            df[col]=pd.to_numeric(df[col],errors="coerce")
        return df
        
data = update_types(data)
print(data.dtypes)

Global_active_power      float64
Global_reactive_power    float64
Voltage                  float64
Global_intensity         float64
Sub_metering_1           float64
dtype: object

In [199]:
data.describe()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1
count,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06
mean,1.091615e+00,1.237145e-01,2.408399e+02,4.627759e+00,1.121923e+00
std,1.057294e+00,1.127220e-01,3.239987e+00,4.444396e+00,6.153031e+00
min,7.600000e-02,0.000000e+00,2.232000e+02,2.000000e-01,0.000000e+00
25%,3.080000e-01,4.800000e-02,2.389900e+02,1.400000e+00,0.000000e+00
50%,6.020000e-01,1.000000e-01,2.410100e+02,2.600000e+00,0.000000e+00
75%,1.528000e+00,1.940000e-01,2.428900e+02,6.400000e+00,0.000000e+00
max,1.112200e+01,1.390000e+00,2.541500e+02,4.840000e+01,8.800000e+01

In [ ]:
print(data.isna().sum())
data.dropna(inplace=True)
print(data.isna().sum())

Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
dtype: int64
Global_active_power      0
Global_reactive_power    0
Voltage                  0
Global_intensity         0
Sub_metering_1           0
dtype: int64

In [201]:
# data["Sub_metering_1"] = pd.to_numeric(data["Sub_metering_1"], errors="coerce")
data.loc[:, "Sub_metering_1"]=(data["Sub_metering_1"]+1)*0.06
data["Sub_metering_1"].head()

Date
2006-12-16    0.06
2006-12-16    0.06
2006-12-16    0.06
2006-12-16    0.06
2006-12-16    0.06
Name: Sub_metering_1, dtype: float64

In [202]:
# data["Voltage"] = pd.to_numeric(data["Voltage"], errors="coerce")

filtered = data[(data.index >="2008-12-27" ) & (data["Voltage"] >= 242.0) ]
# print(filtered.shape)
filtered[["Global_active_power", "Global_reactive_power"]].head()

            Global_active_power  Global_reactive_power
Date
2008-12-27                0.996                  0.066
2008-12-27                1.076                  0.162
2008-12-27                1.064                  0.172
2008-12-27                1.070                  0.174
2008-12-27                0.804                  0.184

In [203]:
data.iloc[88887]

Global_active_power        0.254
Global_reactive_power      0.000
Voltage                  238.100
Global_intensity           1.200
Sub_metering_1             0.060
Name: 2007-02-16 00:00:00, dtype: float64

In [204]:
max_idx = data["Global_active_power"].idxmax()
max_idx

Timestamp('2009-02-22 00:00:00')

In [205]:
result = data.sort_values(
    by=["Global_active_power", "Voltage"],
    ascending=[False, True]
)

result.iloc[:, :3].tail(5)

            Global_active_power  Global_reactive_power  Voltage
Date
2008-08-28                0.076                    0.0   234.88
2008-08-28                0.076                    0.0   235.18
2008-08-28                0.076                    0.0   235.40
2008-08-28                0.076                    0.0   235.64
2008-08-12                0.076                    0.0   236.50

In [209]:
daily_avg = data["Global_active_power"].resample("D").mean()
print(daily_avg)

Date
2006-12-16    3.053475
2006-12-17    2.354486
2006-12-18    1.530435
2006-12-19    1.157079
2006-12-20    1.545658
                ...
2010-11-22    1.417733
2010-11-23    1.095511
2010-11-24    1.247394
2010-11-25    0.993864
2010-11-26    1.178230
Freq: D, Name: Global_active_power, Length: 1442, dtype: float64